library ieee;
use ieee.std_logic_1164.all;
library std;
use std.textio.all;

library work;
use work.veriti.all;

entity add_tb is
    generic (
        LEN : positive := 16
    );
end entity;

architecture sim of add_tb is

    -- This record is auto-generated by Python. DO NOT EDIT.
    type add_bfm is record
        in0  : std_logic_vector(LEN-1 downto 0);
        in1  : std_logic_vector(LEN-1 downto 0);
        cin  : std_logic;
        sum  : std_logic_vector(LEN-1 downto 0);
        cout : std_logic;
    end record;

    signal bfm : add_bfm;

    signal clk  : std_logic;
    signal rst  : std_logic;
    signal halt : boolean := false;

    --! declare internal required testbench signals
    constant TIMEOUT_LIMIT : natural := 1000;

begin
    -- instantiate UUT
    uut : entity work.add
        generic map (
            LEN => LEN
        ) port map (
            cin  => bfm.cin,
            in0  => bfm.in0,
            in1  => bfm.in1,
            sum  => bfm.sum,
            cout => bfm.cout
        );

    --! generate a 50% duty cycle for 25 Mhz
    spin_clock(clk, 40 ns, halt);

    --! test reading a file filled with test vectors
    DRIVER : process
        file inputs : text open read_mode is "inputs.dat";

        -- This procedure is auto-generated by Python. DO NOT EDIT.
        procedure drive_transaction(file fd: text) is 
            variable row : line;
        begin
            if endfile(fd) = false then
                -- drive a transaction
                readline(fd, row);
                drive(row, bfm.in0);
                drive(row, bfm.in1);
                drive(row, bfm.cin);
            end if;
        end procedure; 

    begin  
        -- drive transactions
        while endfile(inputs) = false loop
            drive_transaction(inputs);
            wait until rising_edge(clk);
        end loop;

        -- wait for all outputs to be checked
        wait;
    end process;

    CHECKER : process
        file outputs : text open read_mode is "outputs.dat";
        variable timeout : boolean;

        -- This procedure is auto-generated by Python. DO NOT EDIT.
        procedure scoreboard(file fd: text) is 
            variable row : line;
            variable ideal : add_bfm;
        begin
            if endfile(fd) = false then
                -- compare expected outputs and inputs
                readline(fd, row);
                load(row, ideal.sum);
                assert_eq(bfm.sum, ideal.sum, "sum");
                load(row, ideal.cout);
                assert_eq(bfm.cout, ideal.cout, "cout");
            end if;
        end procedure;

    begin
        while endfile(outputs) = false loop
            -- wait for a valid time to check
            wait until rising_edge(clk);
            -- compare outputs
            scoreboard(outputs);
        end loop;

        -- halt the simulation
        complete(halt);
    end process;

end architecture;