[project]
name = "veriti"
description = "SW drivers for a digital hardware verification framework."
version = "0.1.0"
requires-python = ">=3.7"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"