name: test
on:
  workflow_call:

jobs:
  hw-drivers:
    runs-on: ubuntu-latest
    container:
        image: crus800/fpga-simulation
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Log all tool versions
        run: |
          orbit --version  
          python --version
          ghdl --version
        
      - name: Configure orbit profile
        run: |
          git clone https://github.com/c-rus/orbit-profile.git "$(orbit env ORBIT_HOME)/profiles/crus"
          pip install -r "$(orbit env ORBIT_HOME)/profiles/crus/requirements.txt"
          orbit config --append include="profiles/crus/config.toml"

      - name: Initialize orbit package
        run: |
          orbit init

      - name: Run tests
        run: |
          orbit plan --top t1 --plugin gsim
          orbit b -- --enable-veriti=0 --run-model=1

  sw-drivers:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run tests
        run: |
          python -m unittest sw-drivers/python/src/veriti/*.py

  system:
    runs-on: ubuntu-latest
    container:
        image: crus800/fpga-simulation
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Log all tool versions
        run: |
          orbit --version  
          python --version
          ghdl --version
        
      - name: Configure orbit profile
        run: |
          git clone https://github.com/c-rus/orbit-profile.git "$(orbit env ORBIT_HOME)/profiles/crus"
          pip install -r "$(orbit env ORBIT_HOME)/profiles/crus/requirements.txt"
          orbit config --append include="profiles/crus/config.toml"

      - name: Install veriti software drivers
        run: |
          pip install ./sw-drivers/python

      - name: Initialize orbit package
        run: |
          orbit init

      - name: Test parity module
        run: |
          orbit plan --clean --plugin gsim --top parity
          orbit b
          veriti check --log ./build/gsim/events.log

      - name: Test add module
        run: |
          orbit plan --clean --plugin gsim --top add
          orbit b
          veriti check --log ./build/gsim/events.log

      - name: Test BCD encoder module
        run: |
          orbit plan --clean --plugin gsim --top bcd_enc
          orbit b -- -g LEN=8
          veriti check --log ./build/gsim/events.log
